version: '1'

services:
  db:
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "service_db"
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
